name: Caesar Cipher CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -v

      - name: Lint code
        run: |
          python -m pylint caesar_cipher

      - name: Build and deploy documentation
        run: |
          python -m sphinx -b html docs/source docs/build/html
          mkdir -p docs/build/html/_static
          cp -r docs/source/_static/* docs/build/html/_static/

      - name: Upload documentation to GitHub Pages
        uses: actions/upload-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: docs/build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages